const Cutie = require('../events');

const {MessageType, MessageOptions, Mimetype} = require('@adiwajshing/baileys');

const axios = require('axios');

const Language = require('../language');

const Lang = Language.getString('wallpaper');

Cutie.addCommand({pattern: 'setvar', fromMe: false, desc: Lang.WP}, (async (message, match) => {

    var r_text = new Array ();

    

    

    r_text[0] = "https://i.ibb.co/fkxKnS2/Queen-Cutie.jpg";

    

    

    var i = Math.floor(1*Math.random())

    var respoimage = await axios.get(`${r_text[i]}`, { responseType: 'arraybuffer' })

    await message.sendMessage(Buffer(respoimage.data), MessageType.image, {mimetype: Mimetype.png, caption: `✰━━SETVAR━━✰

╭───────────────────╮
   𝐇𝐞𝐥𝐥𝐨 𝐈 𝐚𝐦 𝐚 𝐐𝐮𝐞𝐞𝐧𝐂𝐮𝐭𝐢𝐞
╰───────────────────╯

│ ▢ 💌All setvar commands💌

╭─────────────────────
│
┣⍟𝕾⃝🌼 To change add message
┣⍟🎲 .setvar ADD_MESSAGE:your message

┣⍟𝕾⃝🌼 To change afk message
┣⍟🎲 .setvar AFK_MESSAGE:your message

┣⍟𝕾⃝🌼 To change alive message
┣⍟🎲 .setvar ALIVE_MESSAGE:your message

┣⍟𝕾⃝🌼 To change captions generated by bot
┣⍟🎲 .setvar ALL_CAPTION:your message

┣⍟𝕾⃝🌼 To change ban message
┣⍟🎲 .setvar BAN_MESSAGE:your message

┣⍟𝕾⃝🌼 To change block message
┣⍟🎲 .setvar BLOCK_MESSAGE:your message

┣⍟𝕾⃝🌼 To block a chat from using bot
┣⍟🎲 .setvar BLOCK_CHAT:chat jid,0,chat jid,0..etc

┣⍟𝕾⃝🌼 To change bot name on .list reply
┣⍟🎲 .setvar BOT_NAME:your BOT name

┣⍟𝕾⃝🌼 To change .leave message
┣⍟🎲 .setvar KICKME_MESSAGE:your message

┣⍟𝕾⃝🌼 To change owner name
┣⍟🎲 .setvar OWNER_NAME:your name

┣⍟𝕾⃝🌼 To change promote message
┣⍟🎲 .setvar PROMOTE_MESSAGE:your message

┣⍟𝕾⃝🌼 To change demote message
┣⍟🎲 .setvar DEMOTE_MESSAGE:your message

┣⍟𝕾⃝🌼 To change handler
┣⍟🎲 .setvar HANDLERS:^[.,!]your handler insidde the box

┣⍟𝕾⃝🌼 To change removebg api key 
┣⍟🎲 .setvar REMOVE_BG_API_KEY:api key

┣⍟𝕾⃝🌼 To change SUDO
┣⍟🎲 .setvar SUDO:number,0,number,0

┣⍟𝕾⃝🌼 To change tagall heading 
┣⍟🎲 .setvar TAG_HEADER:your message

┣⍟𝕾⃝🌼 To change unblock message
┣⍟🎲 .setvar UNBLOCK_MESSAGE:your message

┣⍟𝕾⃝🌼 To change unmute message
┣⍟🎲 .setvar UNMUTE_MESSAGE:your message

┣⍟𝕾⃝🌼 To change work type message
┣⍟🎲 .setvar WORK_TYPE:public or private or admin

┣⍟𝕾⃝🌼 To change bad word remove list
┣⍟🎲 .setvar BADKICK_LIST:badword,badword

┣⍟𝕾⃝🌼 To change QueenCutie bot name
┣⍟🎲 .setvar BOT_NAME:your bot name

┣⍟𝕾⃝🌼 To get a song when your number is mentioned
┣⍟🎲 .setvar TAG_REPPLY:your jid 
│
╰──────────────────────

   ╭──────────────────╮
    *💞Enjoy QueenCutie bot💞*
   ╰──────────────────╯
      ═════💢💢═════

`}) 

}));
